import pick from 'lodash/pick';
import ValidatorStack from '../ValidatorStack';
import validators from '../validators';

export default (validatorsMap = {}) =>
  new ValidatorStack(
    'string',
    {
      ...pick(validators, [
        'isLength',
        'isAlpha',
        'isAlphanumeric',
        'isAscii',
        'isBase64',
        'isCreditCard',
        'isCurrency',
        'isDataURI',
        'isMagnetURI',
        'isDecimal',
        'isEmail',
        'isFQDN',
        'isFullWidth',
        'isHalfWidth',
        'isHash',
        'isHexColor',
        'isHexadecimal',
        'isIdentityCard',
        'isIP',
        'isIPRange',
        'isISBN',
        'isJSON',
        'isJWT',
        'isLatLong',
        'isLowercase',
        'isMD5',
        'isMobilePhone',
        'isMultibyte',
        'isNumeric',
        'isPort',
        'isPostalCode',
        'isURL',
        'isUUID',
        'isUppercase',
        'isVariableWidth',
        'isWhitelisted',
        'isEqual',
        'isEqualWith',
        'isRequired',
        'isValid',
        'isOneOf',
        'isValidNumber',
        'isInteger',
        'isRegExpMatch',
        'isMongoId',
      ]),
      ...validatorsMap,
    },
    [validators.isString()],
  );
